/*
 * plugin.c  –  Wireshark plugin entry points
 *
 * Supports Wireshark 3.x / 4.x plugin API.
 * Do NOT edit this file by hand; it is regenerated by the build system.
 *
 * SPDX-License-Identifier: GPL-2.0-or-later
 */

#include "config.h"

#include <gmodule.h>

/* plugins are shared libraries */
#define WS_BUILD_DLL
#include <ws_symbol_export.h>
#include <epan/proto.h>

#include "moduleinfo.h"

#ifndef ENABLE_STATIC

#ifndef VERSION_RELEASE
# define VERSION_RELEASE "2.6"
#endif

WS_DLL_PUBLIC const char plugin_release[] = VERSION_RELEASE;
WS_DLL_PUBLIC const char plugin_version[] = PLUGIN_VERSION;
#if defined(WIRESHARK_VERSION_MAJOR)
WS_DLL_PUBLIC const int  plugin_want_major = WIRESHARK_VERSION_MAJOR;
WS_DLL_PUBLIC const int  plugin_want_minor = WIRESHARK_VERSION_MINOR;
#endif

extern void proto_register_evil(void);
extern void proto_reg_handoff_evil(void);

WS_DLL_PUBLIC void plugin_register(void);

void
plugin_register(void)
{
    static proto_plugin plug;

    plug.register_protoinfo  = proto_register_evil;
    plug.register_handoff    = proto_reg_handoff_evil;
    proto_register_plugin(&plug);
}

#endif /* ENABLE_STATIC */
